### ISSUE TITLE
Can't access contact records after upgrade to CiviCRM ver5.20.0

### ISSUE THREAD

**Issue by michael-chaplin-gmcvo** [3sd/civicrm-chatbot#17]
After upgrade, we can't access Contact records with the chatbot extension enabled. We get:

CiviCRM_API3_Exception: "Unexpected result from getcountArray ( [error_field] => activity_type_id [error_code] => 2001 [entity] => Activity [action] => get [is_error] => 1 [error_message] => 'Conversation' is not a valid option for field activity_type_id ) "

#0 /home/gmcvodataba5/public_html/sites/default/files/civicrm/extensions/civicrm-chatbot-1.0.0-beta.4/CRM/Chat/Utils.php(44): civicrm_api3("Activity", "getcount", (Array:3))
#1 /home/gmcvodataba5/public_html/sites/default/files/civicrm/extensions/civicrm-chatbot-1.0.0-beta.4/chatbot.php(222): CRM_Chat_Utils::getChatCount("22196")
#2 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(305): chatbot_civicrm_tabs((Array:14), "22196")
#3 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(90): CRM_Utils_Hook->runHooks((Array:174), "civicrm_tabs", 2, (Array:14), "22196", NULL, NULL, NULL, NULL)
#4 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(90): CRM_Utils_Hook_DrupalBase->invokeViaUF(2, (Array:14), "22196", NULL, NULL, NULL, NULL, "civicrm_tabs")
#5 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(184): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_tabs", Object(Civi\Core\CiviEventDispatcher))
#6 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_tabs", Object(Civi\Core\Event\GenericHookEvent))
#7 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_tabs", Object(Civi\Core\Event\GenericHookEvent))
#8 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(187): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_tabs", Object(Civi\Core\Event\GenericHookEvent))
#9 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(806): CRM_Utils_Hook->invoke((Array:2), (Array:14), "22196", NULL, NULL, NULL, NULL, "civicrm_tabs")
#10 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Contact/Page/View/Summary.php(446): CRM_Utils_Hook::tabs((Array:14), "22196")
#11 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Contact/Page/View/Summary.php(276): CRM_Contact_Page_View_Summary->getTabs()
#12 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Contact/Page/View/Summary.php(93): CRM_Contact_Page_View_Summary->view()
#13 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(284): CRM_Contact_Page_View_Summary->run((Array:3), NULL)
#14 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:14))
#15 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#16 /home/gmcvodataba5/public_html/sites/all/modules/civicrm/drupal/civicrm.module(444): CRM_Core_Invoke::invoke((Array:3))
#17 /home/gmcvodataba5/public_html/includes/menu.inc(527): civicrm_invoke("contact", "view")
#18 /home/gmcvodataba5/public_html/index.php(21): menu_execute_active_handler()
#19 {main}
 Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Unexpected result from getcountArray ( [error_field] => activity_type_id [error_code] => 2001 [entity] => Activity [action] => get [is_error] => 1 [error_message] => 'Conversation' is not a valid option for field activity_type_id )

I cannot see 'conversation' as an Activity type in civicrm/admin/options/activity_type?reset=1

Can you help?

Thanks Mike

**Comment by michaelmcandrew** [comment]
Indeed it looks like you no longer have the conversation activity type.

That conversation type is handled here: https://github.com/3sd/civicrm-chatbot/blob/master/managed/activityTypes.mgd.php.

I'm not sure why that has been removed in your case. I would be tempted to re-create it using the details specified in the link above.

That said if you have existing data in there, it is likely to have become corrupted.

One other thing to mention is that this extension is now deprecated in favour of a new extension we are about to start building using Dialogflow, so is unlikely to receive any bug fixes I'm afraid.
